config/routes.rb
Rails.application.routes.draw do
  get 'homepage', to: 'homepage#index'
  get 'contact_us', to: 'homepage#contact_us'
  get 'gallery', to: 'homepage#gallery'
  get 'accommodation', to: 'accommodation#index'
  get 'sea-esta', to: 'accommodation#sea_esta'
  get 'la-palma', to: 'accommodation#la_palma'
  root 'homepage#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/accommodation_controller.rb
class AccommodationController < ApplicationController
  def index
  end

  def sea_esta
  end

  def la_palma
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end

  def accommodation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/accommodation/accommodation.html.erb
<main>
  <section class="hero-section accommodation-hero-section">

  </section>

  <section class="accommodation-section">
    <article class="accommodation-listing">
      <div class="accommodation-listing-upper-container">
        <picture class="accommodation-listing-picture">
          <%= image_tag("blue-ocean.jpg", :alt =>
            "white sand beach", :class => "accommodation-listing-img") %>
        </picture>
        <div class="accommodation-listing-info-container">
          <h2>Sea-Esta</h2>
          <p>Generous rooms offer ample space to relax in our captivating Cape
            Town resort. Your private balcony reveals breathtaking views of
            Table Mountain, our magnificent Marina, or both.
          </p>
        </div>
        <div class="accommodation-listing-contact-container">
          <p class="accommodation-listing-price">$1000/Night</p>
          <button class="accommodation-contact-button" type="button" name="button">
            EXPLORE</button>
        </div>
      </div>
      <!-- <div class="accommodation-listing-lower-container">
        <div class="extra-info">
          <p>blah</p>
          <p>blah</p>
          <p>blah</p>
        </div>
        <a href="#">MORE DETAILS</a>
      </div> -->
    </article>



    <article class="accommodation-listing">
      <div class="accommodation-listing-upper-container">
        <picture class="accommodation-listing-picture">
          <%= image_tag("blue-ocean.jpg", :alt =>
            "white sand beach", :class => "accommodation-listing-img") %>
        </picture>
        <div class="accommodation-listing-info-container">
          <h2>Sea-Esta</h2>
          <p>Generous rooms offer ample space to relax in our captivating Cape
            Town resort. Your private balcony reveals breathtaking views of
            Table Mountain, our magnificent Marina, or both.
          </p>
        </div>
        <div class="accommodation-listing-contact-container">
          <p class="accommodation-listing-price">$1000/Night</p>
          <button class="accommodation-contact-button" type="button" name="button">
            EXPLORE</button>
        </div>
      </div>
      <!-- <div class="accommodation-listing-lower-container">
        <div class="extra-info">
          <p>blah</p>
          <p>blah</p>
          <p>blah</p>
        </div>
        <a href="#">MORE DETAILS</a>
      </div> -->
    </article>



    <article class="accommodation-listing">
      <div class="accommodation-listing-upper-container">
        <picture class="accommodation-listing-picture">
          <%= image_tag("blue-ocean.jpg", :alt =>
            "white sand beach", :class => "accommodation-listing-img") %>
        </picture>
        <div class="accommodation-listing-info-container">
          <h2>Sea-Esta</h2>
          <p>Generous rooms offer ample space to relax in our captivating Cape
            Town resort. Your private balcony reveals breathtaking views of
            Table Mountain, our magnificent Marina, or both.
          </p>
        </div>
        <div class="accommodation-listing-contact-container">
          <p class="accommodation-listing-price">$1000/Night</p>
          <button class="accommodation-contact-button" type="button" name="button">
            EXPLORE</button>
        </div>
      </div>
      <!-- <div class="accommodation-listing-lower-container">
        <div class="extra-info">
          <p>blah</p>
          <p>blah</p>
          <p>blah</p>
        </div>
        <a href="#">MORE DETAILS</a>
      </div> -->
    </article>



    <article class="accommodation-listing">
      <div class="accommodation-listing-upper-container">
        <picture class="accommodation-listing-picture">
          <%= image_tag("blue-ocean.jpg", :alt =>
            "white sand beach", :class => "accommodation-listing-img") %>
        </picture>
        <div class="accommodation-listing-info-container">
          <h2>Sea-Esta</h2>
          <p>Generous rooms offer ample space to relax in our captivating Cape
            Town resort. Your private balcony reveals breathtaking views of
            Table Mountain, our magnificent Marina, or both.
          </p>
        </div>
        <div class="accommodation-listing-contact-container">
          <p class="accommodation-listing-price">$1000/Night</p>
          <button class="accommodation-contact-button" type="button" name="button">
            EXPLORE</button>
        </div>
      </div>
      <!-- <div class="accommodation-listing-lower-container">
        <div class="extra-info">
          <p>blah</p>
          <p>blah</p>
          <p>blah</p>
        </div>
        <a href="#">MORE DETAILS</a>
      </div> -->
    </article>



    
  </section>
</main>

app/views/accommodation/index.html.erb
<main>
  <section class="hero-section accommodation-hero-section">
    <h1 class="accommodation-title">find your accommodation</h1>
  </section>

  <section class="accommodation-section">
    <article class="accommodation-listing">
        <picture class="accommodation-listing-picture">
          <%= image_tag("blue-ocean.jpg", :alt =>
            "white sand beach", :class => "accommodation-listing-img") %>
        </picture>
        <div class="accommodation-listing-info-container">
          <h2>Sea-Esta</h2>
          <p class="listing-price">$1350/night</p>
          <p class="listing-description">Generous rooms offer ample space to relax in our captivating Costa
            Rican Beaches. Your private balcony reveals breathtaking views of
            Jaco Beach.
          </p>
          <a href="/sea-esta" class="accommodation-contact-button">EXPLORE</a>
      </div>
    </article>

    <article class="accommodation-listing">
        <picture class="accommodation-listing-picture">
          <%= image_tag("blue-ocean.jpg", :alt =>
            "white sand beach", :class => "accommodation-listing-img") %>
        </picture>
        <div class="accommodation-listing-info-container">
          <h2>Sea-Esta</h2>
          <p class="listing-price">$1350/night</p>
          <p class="listing-description">Generous rooms offer ample space to relax in our captivating Costa
            Rican Beaches. Your private balcony reveals breathtaking views of
            Jaco Beach.
          </p>
          <a href="/sea-esta" class="accommodation-contact-button">EXPLORE</a>
      </div>
    </article>

    <article class="accommodation-listing">
        <picture class="accommodation-listing-picture">
          <%= image_tag("blue-ocean.jpg", :alt =>
            "white sand beach", :class => "accommodation-listing-img") %>
        </picture>
        <div class="accommodation-listing-info-container">
          <h2>Sea-Esta</h2>
          <p class="listing-price">$1350/night</p>
          <p class="listing-description">Generous rooms offer ample space to relax in our captivating Costa
            Rican Beaches. Your private balcony reveals breathtaking views of
            Jaco Beach.
          </p>
          <a href="/sea-esta" class="accommodation-contact-button">EXPLORE</a>
      </div>
    </article>

    <article class="accommodation-listing">
        <picture class="accommodation-listing-picture">
          <%= image_tag("blue-ocean.jpg", :alt =>
            "white sand beach", :class => "accommodation-listing-img") %>
        </picture>
        <div class="accommodation-listing-info-container">
          <h2>Sea-Esta</h2>
          <p class="listing-price">$1350/night</p>
          <p class="listing-description">Generous rooms offer ample space to relax in our captivating Costa
            Rican Beaches. Your private balcony reveals breathtaking views of
            Jaco Beach.
          </p>
          <a href="/sea-esta" class="accommodation-contact-button">EXPLORE</a>
      </div>
    </article>


  </section>
</main>

app/views/accommodation/sea_esta.html.erb
<main>
  <section class="house-hero-section">
    <picture class="house-hero-picture">
      <%= image_tag("costa-rica-photography-hero-image.jpg", :alt =>
        "costa rican sunset", :class => "house-hero-img") %>
    </picture>
    <div class="house-hero-text">
      <h1>Sea-Esta</h1>
      <p>A stunning home perfected with uninterupted ocean views</p>
    </div>
  </section>
  <section class="house-overview-section">
    <h2>Your home on the beach</h2>
    <p>located in a very special place with lots and lots of things to do</p>
    <article class="house-overview-article">
      <div class="house-info">

      </div>
      <div class="house-overview">
        <h3>House Overview</h3>
        <p>Our Marina Harbour Rooms come with their own private terrace, and
          sit within the seven-storey Marina Rise, a crescent-shaped residence
          designed with traditional South African flair. Choose an inviting
          king-size bed or two generous queen-size beds. Your en suite bathroom,
          complete with dual marble vanities, oval bath and invigorating rain
          shower, is the ideal place to unwind.
        </p>
        <p>If you can tear yourself away from the uplifting views of the harbour,
          indulge in a visit to the hotel’s spectacular Spa Thermal Suites, an
          exclusive benefit for all our Marina Rise guests.
        </p>
      </div>
    </article>
    <aside class="house-extras">
      <div class="house-extras-text">
        <h2>Breakfast with a view</h2>
        <p>In the morning, awaken to breakfast on your private balcony or
          terrace, and be greeted by a golden sunrise. One&Only's Private
          Dining team can cater your perfect meal, as you like.</p>
      </div>
        <picture class="house-extras-picture">

        </picture>

    </aside>
  </section>

  <section class="additional-info-section">
    <p class="banner-text">
      the city is yours to explore
    </p>
    <div class="banner-image">

    </div>
    <article class="additional-houses-article">
      <h2>you may also like</h2>
      <div class="additional-accommodation-container">
        <div class="additional-accommodation">
          <picture class="additional-accommodation-picture">
            <%= image_tag("blue-ocean.jpg", :alt =>
              "white sand beach", :class => "additional-accommodation-img") %>
          </picture>
          <div class="additional-accommodation-info">
            <h3 class="additional-accommodation-title">La Palma</h3>
            <p class="additional-accommodation-description">
              On our lush private island, discover spacious, comfortable rooms
              with your choice of a king-size or two queen-size beds, and magnificent
              marina-facing terraces surrounding the resort's infinity-edge pool.
            </p>
            <a href="#" class="additional-accommodation-link">explore</a>
          </div>
        </div>

        <div class="additional-accommodation">
          <picture class="additional-accommodation-picture">
            <%= image_tag("blue-ocean.jpg", :alt =>
              "white sand beach", :class => "additional-accommodation-img") %>
          </picture>
          <div class="additional-accommodation-info">
            <h3 class="additional-accommodation-title">La Palma</h3>
            <p class="additional-accommodation-description">
              On our lush private island, discover spacious, comfortable rooms
              with your choice of a king-size or two queen-size beds, and magnificent
              marina-facing terraces surrounding the resort's infinity-edge pool.
            </p>
            <a href="#" class="additional-accommodation-link">explore</a>
          </div>
        </div>
      </div>
    </article>
  </section>
</main>

app/views/homepage/gallery.html.erb
<h1>Main#gallery</h1>
<p>Find me in app/views/main/gallery.html.erb</p>

app/views/homepage/index.html.erb
<main>
  <section class="hero-section index-hero-section">
    <picture class="hero-image">
      <%= image_tag("costa-rica-photography-hero-image.jpg", :alt =>
        "costa rican sunset", :class => "hero-img") %>
    </picture>
    <div class="hero-container">
      <div class="hero-title-container">
        <h1>JACO REFINED</h1>
        <p>A Stylish Collection of Luxury Homes in the Coastal Paradise of Jaco, CR</p>
      </div>
      <div class="hero-form-container">
        <!-- <div class="form-select-container">
          <div class="hero-label-container">
            <p>Arrival</p>
          </div>
          <div class="hero-label-container">
            <p>Departure</p>
          </div>
          <div class="hero-label-container">
            <p>Occupancy</p>
          </div>
        </div> -->
        <%= link_to "find a home", accommodation_path, class: "hero-form-button" %>
      </div>
    </div>
  </section>

  <section class="main-section">

      <article>
        <h2 class="article-title">OUR PLEASURE</h2>
        <div class="article-content-container">
          <div class="article-info-container">
            <p>With a collection ranging from opulent mansions to rich hearted villas,
            (Brand name) offers worry free accomadations in paradise. Whether
            you prefer a tropical adventure through land and sea or an indulgent
            and relaxing stay in pure nirvanna, your entire experiance will be hand
            crafted by the most talented purvayours of splendor on the continent.</p>
            <ul class="article-list">
              <li>Artfully Curated</li>
              <li>Luxury Homes</li>
              <li>Relaxing Spaces</li>
              <li><button class="article-list-button" type="button" name="button">View Gallery</button></li>
            </ul>
          </div>
          <div class="article-image-container">
            <picture>
              <%= image_tag("blue-ocean.jpg", :alt =>
                "white sand beach", :class => "article-main-img") %>
            </picture>
          </div>
        </div>

      </article>

      <article>
        <h2 class="article-title">ACCOMMODATIONS</h2>
        <div class="article-content-container reverse-article">
          <div class="article-info-container">
            <h3>Our Homes</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer
              metus felis, dapibus commodo tortor a, pulvinar sodales est.
              Maecenas quis molestie libero. Donec vehicula nibh ante, at aliquet
              leo sodales ac. Curabitur sed tincidunt justo. Lorem ipsum dolor sit
              amet, consectetur adipiscing elit. Nunc at sem a quam dictum
              tincidunt ut vel lacus. Nunc quis massa eget metus cursus malesuada.
              Duis lobortis ante ac elementum sagittis. Nam at ante sed velit elementum
              imperdiet euismod a dui. Nullam congue turpis eu velit congue euismod.
            </p>
              <div class="space-divider"></div>
            <h3>Offered Accommodations</h3>
            <p>Nunc diam lacus, semper vitae maximus et, luctus ac felis. Pellentesque
              ligula massa, hendrerit in augue eget.
            </p>
            <%= link_to "Click Here", accommodation_path, class: "article-link" %>
          </div>
          <div class="article-image-container">
            <picture>
              <%= image_tag("blue-ocean.jpg", :alt =>
                "white sand beach", :class => "article-main-img") %>
            </picture>
          </div>
        </div>
      </article>


      <article>
        <h2 class="article-title">YOUR ADVENTURE</h2>
        <div class="article-content-container">
          <div class="article-info-container">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit
            n voluptate velit esse cillum dolore eu fugiat nulla pariatur</p>
            <ul class="article-list guest-rooms-list">
              <li>Bananas</li>
              <li>Mangos</li>
              <li>Chocolates</li>
              <li>Heavy Petting</li>
            </ul>
          </div>
          <div class="article-image-container">
            <picture>
              <%= image_tag("blue-ocean.jpg", :alt =>
                "white sand beach", :class => "article-main-img") %>
            </picture>
          </div>
        </div>
      </article>

      <article class="get-on-the-list-article">
        <div class="get-on-the-list-top-container">
          <div class="top-left-outline-get-on-the-list"></div>
          <h2 class="list-article-title">GET ON THE LIST</h2>
          <div class="top-right-outline-get-on-the-list"></div>
        </div>
        <div class="get-on-the-list-content-container">
          <div class="get-on-the-list-image-container">
            <picture class="get-on-the-list-picture">
              <%= image_tag("blue-ocean.jpg", :alt =>
                "white sand beach", :class => "get-on-the-list-main-img") %>
            </picture>
          </div>
          <div class="get-on-the-list-info-container">
            <div class="get-on-the-list-text-container">
              <p>Curious to know more? Sign-up and we’ll keep you posted on property
                updates and promotions.
              </p>
              <!-- insert minor form here -->
            </div>
          </div>
        </div>
      </article>
      <article class="location-article">
        <h2 class="article-title">OUR Location</h2>
        <div class="article-content-container reverse-article">
          <div class="article-info-container">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat.
            </p>
            <ul class="article-list guest-rooms-list">
              <li><a class="map-link" href="#">Jaco Costa Rica</a></li>
            </ul>
          </div>
          <div class="article-image-container">
            <picture>
              <%= image_tag("blue-ocean.jpg", :alt =>
                "white sand beach", :class => "article-main-img") %>
            </picture>
          </div>
        </div>
      </article>
  </section>
</main>

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer-head">
    <h1>Find Your Home</h1>
  </div>
  <div class="footer-image-conatainer">
    <picture class="footer-picture">
      <%= image_tag("blue-ocean.jpg", :alt =>
        "white sand beach", :class => "footer-img") %>
    </picture>
    <picture class="footer-picture">
      <%= image_tag("blue-ocean.jpg", :alt =>
        "white sand beach", :class => "footer-img") %>
    </picture>
    <picture class="footer-picture">
      <%= image_tag("blue-ocean.jpg", :alt =>
        "white sand beach", :class => "footer-img") %>
    </picture>
    <picture class="footer-picture">
      <%= image_tag("blue-ocean.jpg", :alt =>
        "white sand beach", :class => "footer-img") %>
    </picture>
  </div>
  <div class="footer-directory">
    <%= link_to "Homepage", homepage_path %>
    <%= link_to "Accomadations", accommodation_path %>
    <%= link_to "Gallery", accommodation_path %>
    <%= link_to "About Us", accommodation_path %>
    <%= link_to "Experiences", accommodation_path %>
  </div>
  <div class="footer-end">
    <p>Congratulations on reaching the bottom of the page :)</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="mobile-menu-background"></div>
  <button aria-expanded="false" class="mobile-nav-toggle"></button>
  <div class="primary-navigation" data-visible="false">
    <div class="placeholder-logo"></div>
    <nav>
      <ul class="nav-list">
        <li><%= link_to "Homepage", homepage_path, class: "nav-link" %></li>
        <li><%= link_to "Accomadations", accommodation_path, class: "nav-link" %></li>
        <li><%= link_to "Gallery", accommodation_path, class: "nav-link" %></li>
        <li><%= link_to "About Us", accommodation_path, class: "nav-link" %></li>
        <li><%= link_to "Experiences", accommodation_path, class: "nav-link" %></li>
      </ul>
    </nav>
    <%= link_to "Contact Us", contact_us_path, class: "header-contact-us-btn" %>
  </div>
</header>

app/views/layouts/accommodation.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Website</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'accommodation/accommodation', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Website</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/homepage.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Website</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'homepage/homepage', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>